### ISSUE TITLE
Dataset is not accessible

### ISSUE THREAD

**Issue by lxysl** [Grid-Gudx/LGAN-PQD#1]
The link of your dataset on Baidu Netdisk is not accessible. How can I get it?

**Comment by Grid-Gudx** [comment]
the link of datasets have been updated

**Comment by Grid-Gudx** [comment]
> The link of your dataset on Baidu Netdisk is not accessible. How can I get it?

the link of datasets have been updated

**Comment by lxysl** [comment]
Thank you but the password is not correct?

**Comment by Grid-Gudx** [comment]
> Thank you but the password is not correct?

我检查了下，没问题呀

**Comment by lxysl** [comment]
Now is okey, thanks!

**Comment by Pr0mise-zkx** [comment]
请问数据集中包含了高斯噪声吗

**Comment by Grid-Gudx** [comment]
包含的




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Grid-Gudx/LGAN-PQD"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年11月4日(星期五) 中午12:48
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Grid-Gudx/LGAN-PQD] Dataset is not accessible (Issue #1)





 
请问数据集中包含了高斯噪声吗
